# Imports

In [20]:
import pandas as pd
import numpy as np
import pgeocode

# Data

In [3]:
df = pd.read_parquet('./data/pp-complete.parquet')
df.head()

,price,date,postcode,type,old_new,duration,PAON SAON,street,locality,town_city,district,county,ppd_type
0,166500,1995-11-22,CM23 4PA,D,Y,F,19,MAYFLOWER GARDENS,BISHOP'S STORTFORD,BISHOP'S STORTFORD,EAST HERTFORDSHIRE,HERTFORDSHIRE,A
1,59000,1995-09-27,L12 0AY,D,N,L,7,TRENT CLOSE,LIVERPOOL,LIVERPOOL,LIVERPOOL,MERSEYSIDE,A
2,118000,1995-12-15,SL3 8XX,D,N,F,24,SOUTHWOLD SPUR,SLOUGH,SLOUGH,SLOUGH,SLOUGH,A
3,48500,1995-01-27,CV12 8TF,S,N,F,5,CHELTENHAM CLOSE,BEDWORTH,BEDWORTH,NUNEATON AND BEDWORTH,WARWICKSHIRE,A
4,27500,1995-04-20,SY11 1HP,S,N,F,105,BEATRICE STREET,OSWESTRY,OSWESTRY,OSWESTRY,SHROPSHIRE,A

In [4]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
first_date = df['date'].min()
df['passed'] = (df['date'] - first_date).dt.days

df.drop(columns=['date'], inplace=True)

df.head()

,price,postcode,type,old_new,duration,PAON SAON,street,locality,town_city,district,county,ppd_type,year,month,passed
0,166500,CM23 4PA,D,Y,F,19,MAYFLOWER GARDENS,BISHOP'S STORTFORD,BISHOP'S STORTFORD,EAST HERTFORDSHIRE,HERTFORDSHIRE,A,1995,11,325
1,59000,L12 0AY,D,N,L,7,TRENT CLOSE,LIVERPOOL,LIVERPOOL,LIVERPOOL,MERSEYSIDE,A,1995,9,269
2,118000,SL3 8XX,D,N,F,24,SOUTHWOLD SPUR,SLOUGH,SLOUGH,SLOUGH,SLOUGH,A,1995,12,348
3,48500,CV12 8TF,S,N,F,5,CHELTENHAM CLOSE,BEDWORTH,BEDWORTH,NUNEATON AND BEDWORTH,WARWICKSHIRE,A,1995,1,26
4,27500,SY11 1HP,S,N,F,105,BEATRICE STREET,OSWESTRY,OSWESTRY,OSWESTRY,SHROPSHIRE,A,1995,4,109

# Functions

In [25]:
def haversine(lat1, lon1, lat2, lon2):
    """
    Все аргументы в градусах, возвращает расстояние в километрах.
    """
    # переводим в радианы
    φ1, φ2 = np.radians(lat1), np.radians(lat2)
    Δφ = np.radians(lat2 - lat1)
    Δλ = np.radians(lon2 - lon1)

    a = np.sin(Δφ/2)**2 + np.cos(φ1)*np.cos(φ2)*np.sin(Δλ/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    R = 6371.0  # средний радиус Земли в км

    return R * c

# Feature Engineering

In [ ]:
district_counts = df['district'].value_counts().reset_index()
district_counts.columns = ['district', 'count']

# Получаем список названий district, где число упоминаний < 100
low_count_districts = district_counts[district_counts['count'] < 100]['district'].tolist()

# Удаляем эти районы из основного датафрейма
df = df[~df['district'].isin(low_count_districts)]

df['median_price_all_type'] = df.groupby(['type', 'old_new', 'duration', 'ppd_type', 'district', 'year', 'month'])['price'].transform('median')
df.head(10)

,price,postcode,type,old_new,duration,PAON SAON,street,locality,town_city,district,county,ppd_type,year,month,passed,median_price_all_type
0,166500,CM23 4PA,D,Y,F,19,MAYFLOWER GARDENS,BISHOP'S STORTFORD,BISHOP'S STORTFORD,EAST HERTFORDSHIRE,HERTFORDSHIRE,A,1995,11,325,140000.0
1,59000,L12 0AY,D,N,L,7,TRENT CLOSE,LIVERPOOL,LIVERPOOL,LIVERPOOL,MERSEYSIDE,A,1995,9,269,55000.0
2,118000,SL3 8XX,D,N,F,24,SOUTHWOLD SPUR,SLOUGH,SLOUGH,SLOUGH,SLOUGH,A,1995,12,348,106000.0
3,48500,CV12 8TF,S,N,F,5,CHELTENHAM CLOSE,BEDWORTH,BEDWORTH,NUNEATON AND BEDWORTH,WARWICKSHIRE,A,1995,1,26,48000.0
4,27500,SY11 1HP,S,N,F,105,BEATRICE STREET,OSWESTRY,OSWESTRY,OSWESTRY,SHROPSHIRE,A,1995,4,109,43000.0
5,114000,SE24 0DH,S,N,F,13,BRANTWOOD ROAD,LONDON,LONDON,LAMBETH,GREATER LONDON,A,1995,6,180,95750.0
6,46000,TS10 2DJ,S,N,F,2,MALCOLM GROVE,REDCAR,REDCAR,LANGBAURGH-ON-TEES,CLEVELAND,A,1995,9,262,44500.0
7,52500,SN2 2SY,S,N,F,11,MARIGOLD CLOSE,SWINDON,SWINDON,THAMESDOWN,THAMESDOWN,A,1995,5,131,55250.0
8,19000,PO32 6EP,T,N,F,17,CLARENCE ROAD,EAST COWES,EAST COWES,ISLE OF WIGHT,ISLE OF WIGHT,A,1995,10,302,37750.0
9,67500,SE18 2DH,T,N,F,75,HIGHMEAD,LONDON,LONDON,GREENWICH,GREATER LONDON,A,1995,11,320,55000.0

In [18]:
nomi = pgeocode.Nominatim("gb")

# запрос сразу по вектору — вернёт DataFrame с полями latitude/longitude и прочими
geo = nomi.query_postal_code(df["postcode"].tolist())

df["latitude"]  = geo["latitude"].values
df["longitude"] = geo["longitude"].values

df.drop(columns=['postcode'], inplace=True)
df.dropna(subset=["latitude", "longitude"], inplace=True)

df.head()

,price,type,old_new,duration,PAON SAON,street,locality,town_city,district,county,ppd_type,year,month,passed,median_price_all_type,latitude,longitude
0,166500,D,Y,F,19,MAYFLOWER GARDENS,BISHOP'S STORTFORD,BISHOP'S STORTFORD,EAST HERTFORDSHIRE,HERTFORDSHIRE,A,1995,11,325,140000.0,51.895390,0.156180
1,59000,D,N,L,7,TRENT CLOSE,LIVERPOOL,LIVERPOOL,LIVERPOOL,MERSEYSIDE,A,1995,9,269,55000.0,53.432800,-2.909600
2,118000,D,N,F,24,SOUTHWOLD SPUR,SLOUGH,SLOUGH,SLOUGH,SLOUGH,A,1995,12,348,106000.0,51.502114,-0.551257
3,48500,S,N,F,5,CHELTENHAM CLOSE,BEDWORTH,BEDWORTH,NUNEATON AND BEDWORTH,WARWICKSHIRE,A,1995,1,26,48000.0,52.478075,-1.447600
4,27500,S,N,F,105,BEATRICE STREET,OSWESTRY,OSWESTRY,OSWESTRY,SHROPSHIRE,A,1995,4,109,43000.0,52.832861,-2.965928

In [ ]:
#TODO Расчет расстояния до ближайшего города
#TODO Расчет расстояния до ближайшего крупного города
#TODO Расчет населения/числа продаж города
#TODO Добавить дискреты is_big_city/is_crysis
#TODO Добавить сопутствующие экономические метрики: ср.зарплата/инфляция/безработица

In [22]:
from geopy.geocoders import Nominatim
import time

# Инициализируем геокодер
geolocator = Nominatim(user_agent="my_geocoder")

# Прогоним все уникальные города
city_coords = {}
nn = 0
for city in df['town_city'].unique():
    try:
        nn += 1
        loc = geolocator.geocode(f"{city}, UK")
        if loc:
            city_coords[city] = (loc.latitude, loc.longitude)
            print(f"Добавлен город {nn}/{len(df['town_city'].unique())}: {city}")
        else:
            city_coords[city] = (None, None)
            print(f"Ошибка при добавлении города {nn}/{len(df['town_city'].unique())}: {city}")
    except Exception:
        city_coords[city] = (None, None)
    #time.sleep(1)  # Нужная задержка между запросами (1 запрос в секунду)

Добавлен город 1/1172: BISHOP'S STORTFORD
Добавлен город 2/1172: LIVERPOOL
Добавлен город 3/1172: SLOUGH
Добавлен город 4/1172: BEDWORTH
Добавлен город 5/1172: OSWESTRY
Добавлен город 6/1172: LONDON
Добавлен город 7/1172: REDCAR
Добавлен город 8/1172: SWINDON
Добавлен город 9/1172: EAST COWES
Добавлен город 10/1172: STAFFORD
Добавлен город 11/1172: DAGENHAM
Добавлен город 12/1172: CREWE
Добавлен город 13/1172: HALIFAX
Добавлен город 14/1172: CREWKERNE
Добавлен город 15/1172: WORTHING
Добавлен город 16/1172: WORCESTER
Добавлен город 17/1172: LEEDS
Добавлен город 18/1172: WETHERBY
Добавлен город 19/1172: OAKHAM
Добавлен город 20/1172: DURHAM
Добавлен город 21/1172: WIGAN
Добавлен город 22/1172: BEDFORD
Добавлен город 23/1172: ROCHESTER
Добавлен город 24/1172: EAST GRINSTEAD
Добавлен город 25/1172: LLANRWST
Добавлен город 26/1172: LEICESTER
Добавлен город 27/1172: LINCOLN
Добавлен город 28/1172: BRISTOL
Добавлен город 29/1172: YORK
Добавлен город 30/1172: BRACKNELL
Добавлен город 31/1172: HEBBURN
Добавлен город 32/1172: DEESIDE
Добавлен город 33/1172: DEVIZES
Добавлен город 34/1172: HONITON
Добавлен город 35/1172: WASHINGTON
Добавлен город 36/1172: CANNOCK
Добавлен город 37/1172: ELY
Добавлен город 38/1172: WEMBLEY
Добавлен город 39/1172: SUTTON COLDFIELD
Добавлен город 40/1172: BRIDGEND
Добавлен город 41/1172: MAIDSTONE
Добавлен город 42/1172: NEWCASTLE
Добавлен город 43/1172: HUNSTANTON
Добавлен город 44/1172: CANTERBURY
Добавлен город 45/1172: HOUGHTON LE SPRING
Добавлен город 46/1172: WEST BYFLEET
Добавлен город 47/1172: HALESOWEN
Добавлен город 48/1172: STRATFORD-UPON-AVON
Добавлен город 49/1172: DARWEN
Добавлен город 50/1172: LLANDOVERY
Добавлен город 51/1172: PLYMOUTH
Добавлен город 52/1172: SWADLINCOTE
Добавлен город 53/1172: BURTON-ON-TRENT
Добавлен город 54/1172: DUNMOW
Добавлен город 55/1172: VENTNOR
Добавлен город 56/1172: WATCHET
Добавлен город 57/1172: SUNDERLAND
Добавлен город 58/1172: BRIDGWATER
Добавлен город 59/1172: ANDOVER
Добавлен город 60/1172: CHIPPENHAM
Добавлен город 61/1172: SOUTHEND-ON-SEA
Добавлен город 62/1172: NORTHAMPTON
Добавлен город 63/1172: SHIPSTON-ON-STOUR
Добавлен город 64/1172: EPPING
Добавлен город 65/1172: DARLINGTON
Добавлен город 66/1172: CHELTENHAM
Добавлен город 67/1172: ASHFORD
Добавлен город 68/1172: CLITHEROE
Добавлен город 69/1172: ABERYSTWYTH
Добавлен город 70/1172: GRIMSBY
Добавлен город 71/1172: SKEGNESS
Добавлен город 72/1172: GATESHEAD
Добавлен город 73/1172: HARTLEPOOL
Добавлен город 74/1172: CALDICOT
Добавлен город 75/1172: CAMBRIDGE
Добавлен город 76/1172: BASILDON
Добавлен город 77/1172: BANWELL
Добавлен город 78/1172: STOCKPORT
Добавлен город 79/1172: ALDERSHOT
Добавлен город 80/1172: SOUTHAMPTON
Добавлен город 81/1172: DORKING
Добавлен город 82/1172: BEDALE
Добавлен город 83/1172: SWANSEA
Добавлен город 84/1172: CHERTSEY
Добавлен город 85/1172: SHEFFIELD
Добавлен город 86/1172: NORWICH
Добавлен город 87/1172: RUISLIP
Добавлен город 88/1172: PRESTON
Добавлен город 89/1172: WHITSTABLE
Добавлен город 90/1172: NORTH SHIELDS
Добавлен город 91/1172: HEMEL HEMPSTEAD
Добавлен город 92/1172: HENGOED
Добавлен город 93/1172: THIRSK
Добавлен город 94/1172: FAREHAM
Добавлен город 95/1172: LOUGHBOROUGH
Добавлен город 96/1172: HULL
Добавлен город 97/1172: STOKE-SUB-HAMDON
Добавлен город 98/1172: ISLEWORTH
Добавлен город 99/1172: REIGATE
Добавлен город 100/1172: ROCHDALE
Добавлен город 101/1172: CHATHAM
Добавлен город 102/1172: MANCHESTER
Добавлен город 103/1172: WATFORD
Добавлен город 104/1172: HARLOW
Добавлен город 105/1172: CARNFORTH
Добавлен город 106/1172: ST. IVES
Добавлен город 107/1172: BATH
Добавлен город 108/1172: PORTSMOUTH
Добавлен город 109/1172: BODMIN
Добавлен город 110/1172: REDDITCH
Добавлен город 111/1172: NEWTON ABBOT
Добавлен город 112/1172: WAKEFIELD
Добавлен город 113/1172: POLEGATE
Добавлен город 114/1172: WOODBRIDGE
Добавлен город 115/1172: HARROW
Добавлен город 116/1172: BUSHEY
Добавлен город 117/1172: PEMBROKE DOCK
Добавлен город 118/1172: CARDIFF
Добавлен город 119/1172: BUDLEIGH SALTERTON
Добавлен город 120/1172: LEAMINGTON SPA
Добавлен город 121/1172: SOUTH CROYDON
Добавлен город 122/1172: BRECON
Добавлен город 123/1172: WISBECH
Добавлен город 124/1172: SUTTON
Добавлен город 125/1172: HAVANT
Добавлен город 126/1172: STONE
Добавлен город 127/1172: TWICKENHAM
Добавлен город 128/1172: HALSTEAD
Добавлен город 129/1172: PENZANCE
Добавлен город 130/1172: BLACKWOOD
Добавлен город 131/1172: UXBRIDGE
Добавлен город 132/1172: BIGGLESWADE
Добавлен город 133/1172: BURNLEY
Добавлен город 134/1172: BEACONSFIELD
Добавлен город 135/1172: STEVENAGE
Добавлен город 136/1172: GILLINGHAM
Добавлен город 137/1172: ROTHERHAM
Добавлен город 138/1172: COVENTRY
Добавлен город 139/1172: BOURNEMOUTH
Добавлен город 140/1172: MIDHURST
Добавлен город 141/1172: HESSLE
Добавлен город 142/1172: MARCH
Добавлен город 143/1172: KETTERING
Добавлен город 144/1172: WELWYN
Добавлен город 145/1172: WICKFORD
Добавлен город 146/1172: BANBURY
Добавлен город 147/1172: HORSHAM
Добавлен город 148/1172: WILMSLOW
Добавлен город 149/1172: HOLMFIRTH
Добавлен город 150/1172: BRIXHAM
Добавлен город 151/1172: HYDE
Добавлен город 152/1172: STONEHOUSE
Добавлен город 153/1172: WOLVERHAMPTON
Добавлен город 154/1172: WIDNES
Добавлен город 155/1172: WELLINGTON
Добавлен город 156/1172: BARNSTAPLE
Добавлен город 157/1172: LYDBROOK
Добавлен город 158/1172: CHINNOR
Добавлен город 159/1172: AXBRIDGE
Добавлен город 160/1172: MACHYNLLETH
Добавлен город 161/1172: WARWICK
Добавлен город 162/1172: WINDLESHAM
Добавлен город 163/1172: SAWBRIDGEWORTH
Добавлен город 164/1172: WITNEY
Добавлен город 165/1172: SUDBURY
Добавлен город 166/1172: SALISBURY
Добавлен город 167/1172: ST NEOTS
Добавлен город 168/1172: UPMINSTER
Добавлен город 169/1172: LYMINGTON
Добавлен город 170/1172: PETERSFIELD
Добавлен город 171/1172: SPALDING
Добавлен город 172/1172: HAVERFORDWEST
Добавлен город 173/1172: GLOUCESTER
Добавлен город 174/1172: GREAT YARMOUTH
Добавлен город 175/1172: KING'S LYNN
Добавлен город 176/1172: TAUNTON
Добавлен город 177/1172: CHEPSTOW
Добавлен город 178/1172: RHAYADER
Добавлен город 179/1172: LAUNCESTON
Добавлен город 180/1172: FOWEY
Добавлен город 181/1172: SOUTH MOLTON
Добавлен город 182/1172: ST LEONARDS-ON-SEA
Добавлен город 183/1172: CROMER
Добавлен город 184/1172: NOTTINGHAM
Добавлен город 185/1172: WINSCOMBE
Добавлен город 186/1172: LLANYMYNECH
Добавлен город 187/1172: LAMPETER
Добавлен город 188/1172: ABERTILLERY
Добавлен город 189/1172: MENAI BRIDGE
Добавлен город 190/1172: SOLIHULL
Добавлен город 191/1172: HUDDERSFIELD
Добавлен город 192/1172: STOKE-ON-TRENT
Добавлен город 193/1172: OTTERY ST MARY
Добавлен город 194/1172: SIDMOUTH
Добавлен город 195/1172: BIRMINGHAM
Добавлен город 196/1172: BLACKPOOL
Добавлен город 197/1172: WIRRAL
Добавлен город 198/1172: WELLS-NEXT-THE-SEA
Добавлен город 199/1172: NEWCASTLE UPON TYNE
Добавлен город 200/1172: LLANDRINDOD WELLS
Добавлен город 201/1172: CHICHESTER
Добавлен город 202/1172: CONSETT
Добавлен город 203/1172: MAIDENHEAD
Добавлен город 204/1172: HELSTON
Добавлен город 205/1172: YELVERTON
Добавлен город 206/1172: LOUTH
Добавлен город 207/1172: OKEHAMPTON
Добавлен город 208/1172: BLACKBURN
Добавлен город 209/1172: MARKET RASEN
Добавлен город 210/1172: PONTYPOOL
Добавлен город 211/1172: WREXHAM
Добавлен город 212/1172: KEIGHLEY
Добавлен город 213/1172: MILTON KEYNES
Добавлен город 214/1172: COLCHESTER
Добавлен город 215/1172: BRIERLEY HILL
Добавлен город 216/1172: PETERBOROUGH
Добавлен город 217/1172: MACCLESFIELD
Добавлен город 218/1172: WALSALL
Добавлен город 219/1172: BECKENHAM
Добавлен город 220/1172: NORTHOLT
Добавлен город 221/1172: CORBRIDGE
Добавлен город 222/1172: SLEAFORD
Добавлен город 223/1172: LUTON
Добавлен город 224/1172: HOVE
Добавлен город 225/1172: ASHBY-DE-LA-ZOUCH
Добавлен город 226/1172: CHALFONT ST. GILES
Добавлен город 227/1172: BELPER
Добавлен город 228/1172: HEREFORD
Добавлен город 229/1172: CHIPPING NORTON
Добавлен город 230/1172: DOVER
Добавлен город 231/1172: OLDHAM
Добавлен город 232/1172: SOUTHWELL
Добавлен город 233/1172: STREET
Добавлен город 234/1172: MARGATE
Добавлен город 235/1172: ILFORD
Добавлен город 236/1172: FARNBOROUGH
Добавлен город 237/1172: BOGNOR REGIS
Добавлен город 238/1172: READING
Добавлен город 239/1172: NEWPORT
Добавлен город 240/1172: IPSWICH
Добавлен город 241/1172: CANVEY ISLAND
Добавлен город 242/1172: LEIGH-ON-SEA
Добавлен город 243/1172: BECCLES
Добавлен город 244/1172: SHEERNESS
Добавлен город 245/1172: HAVERHILL
Добавлен город 246/1172: WESTON-SUPER-MARE
Добавлен город 247/1172: BEVERLEY
Добавлен город 248/1172: BILLINGHAM
Добавлен город 249/1172: PICKERING
Добавлен город 250/1172: LEIGH
Добавлен город 251/1172: MANSFIELD
Добавлен город 252/1172: BRIGHTON
Добавлен город 253/1172: SELBY
Добавлен город 254/1172: NUNEATON
Добавлен город 255/1172: JARROW
Добавлен город 256/1172: OXFORD
Добавлен город 257/1172: TAMWORTH
Добавлен город 258/1172: BROXBOURNE
Добавлен город 259/1172: COBHAM
Добавлен город 260/1172: BOOTLE
Добавлен город 261/1172: SOUTHSEA
Добавлен город 262/1172: GRAYS
Добавлен город 263/1172: MIDDLEWICH
Добавлен город 264/1172: CLEATOR MOOR
Добавлен город 265/1172: YEOVIL
Добавлен город 266/1172: DONCASTER
Добавлен город 267/1172: THORNTON-CLEVELEYS
Добавлен город 268/1172: PUDSEY
Добавлен город 269/1172: FELIXSTOWE
Добавлен город 270/1172: BARRY
Добавлен город 271/1172: SCARBOROUGH
Добавлен город 272/1172: BUCKLEY
Добавлен город 273/1172: HARROGATE
Добавлен город 274/1172: COTTINGHAM
Добавлен город 275/1172: LITTLEHAMPTON
Добавлен город 276/1172: STOURBRIDGE
Добавлен город 277/1172: NEWTON-LE-WILLOWS
Добавлен город 278/1172: WARRINGTON
Добавлен город 279/1172: BURGESS HILL
Добавлен город 280/1172: ALTON
Добавлен город 281/1172: TELFORD
Добавлен город 282/1172: BALDOCK
Добавлен город 283/1172: DUNSTABLE
Добавлен город 284/1172: NEWBURY
Добавлен город 285/1172: CHARD
Добавлен город 286/1172: DIDCOT
Добавлен город 287/1172: GRANTHAM
Добавлен город 288/1172: NEWMARKET
Добавлен город 289/1172: OXTED
Добавлен город 290/1172: PORTHCAWL
Добавлен город 291/1172: SEVENOAKS
Добавлен город 292/1172: CHELMSFORD
Добавлен город 293/1172: WALLASEY
Добавлен город 294/1172: BUCKINGHAM
Добавлен город 295/1172: BRENTWOOD
Добавлен город 296/1172: COLWYN BAY
Добавлен город 297/1172: BOREHAMWOOD
Добавлен город 298/1172: ADDLESTONE
Добавлен город 299/1172: CARSHALTON
Добавлен город 300/1172: BRACKLEY
Добавлен город 301/1172: BROMLEY
Добавлен город 302/1172: DEWSBURY
Добавлен город 303/1172: ILKLEY
Добавлен город 304/1172: NORTHALLERTON
Добавлен город 305/1172: RADSTOCK
Добавлен город 306/1172: BRIDGNORTH
Добавлен город 307/1172: HEATHFIELD
Добавлен город 308/1172: WESTBURY
Добавлен город 309/1172: BANSTEAD
Добавлен город 310/1172: KNOTTINGLEY
Добавлен город 311/1172: SHANKLIN
Добавлен город 312/1172: EBBW VALE
Добавлен город 313/1172: EASTBOURNE
Добавлен город 314/1172: BURY
Добавлен город 315/1172: SHREWSBURY
Добавлен город 316/1172: GREENFORD
Добавлен город 317/1172: SMETHWICK
Добавлен город 318/1172: STAINES
Добавлен город 319/1172: HERNE BAY
Добавлен город 320/1172: PRESTATYN
Добавлен город 321/1172: RUGELEY
Добавлен город 322/1172: MORECAMBE
Добавлен город 323/1172: BRIGHOUSE
Добавлен город 324/1172: BRADFORD
Добавлен город 325/1172: DORCHESTER
Добавлен город 326/1172: HOUNSLOW
Добавлен город 327/1172: MATLOCK
Добавлен город 328/1172: THAME
Добавлен город 329/1172: DERBY
Добавлен город 330/1172: HUNTINGDON
Добавлен город 331/1172: YARM
Добавлен город 332/1172: CHESHAM
Добавлен город 333/1172: GUILDFORD
Добавлен город 334/1172: MALDON
Добавлен город 335/1172: RETFORD
Добавлен город 336/1172: MABLETHORPE
Добавлен город 337/1172: TORQUAY
Добавлен город 338/1172: KENDAL
Добавлен город 339/1172: CARLISLE
Добавлен город 340/1172: BEAWORTHY
Добавлен город 341/1172: BUXTON
Добавлен город 342/1172: WHITBY
Добавлен город 343/1172: BURY ST EDMUNDS
Добавлен город 344/1172: TRURO
Добавлен город 345/1172: REDRUTH
Добавлен город 346/1172: DARTMOUTH
Добавлен город 347/1172: VIRGINIA WATER
Добавлен город 348/1172: ABERGELE
Добавлен город 349/1172: RYE
Добавлен город 350/1172: STROUD
Добавлен город 351/1172: MALVERN
Добавлен город 352/1172: BEXHILL-ON-SEA
Добавлен город 353/1172: MORETON-IN-MARSH
Добавлен город 354/1172: WOTTON-UNDER-EDGE
Добавлен город 355/1172: LUDLOW
Добавлен город 356/1172: CARDIGAN
Добавлен город 357/1172: LISKEARD
Добавлен город 358/1172: RADLETT
Добавлен город 359/1172: SOUTH SHIELDS
Добавлен город 360/1172: HENLEY-ON-THAMES
Добавлен город 361/1172: COLEFORD
Добавлен город 362/1172: WHITCHURCH
Добавлен город 363/1172: DISS
Добавлен город 364/1172: KILGETTY
Добавлен город 365/1172: NEWARK
Добавлен город 366/1172: HARLESTON
Добавлен город 367/1172: KIDDERMINSTER
Добавлен город 368/1172: LEATHERHEAD
Добавлен город 369/1172: ST. ALBANS
Добавлен город 370/1172: EXETER
Добавлен город 371/1172: HORNCHURCH
Добавлен город 372/1172: BILLINGSHURST
Добавлен город 373/1172: BIDEFORD
Добавлен город 374/1172: RICHMOND
Добавлен город 375/1172: TEDDINGTON
Добавлен город 376/1172: HASTINGS
Добавлен город 377/1172: CORBY
Добавлен город 378/1172: HERTFORD
Добавлен город 379/1172: LOUGHTON
Добавлен город 380/1172: BLYTH
Добавлен город 381/1172: CRAWLEY
Добавлен город 382/1172: WIGTON
Добавлен город 383/1172: BROMSGROVE
Добавлен город 384/1172: CHESTERFIELD
Добавлен город 385/1172: CATERHAM
Добавлен город 386/1172: CHESTER LE STREET
Добавлен город 387/1172: TIVERTON
Добавлен город 388/1172: AYLESBURY
Добавлен город 389/1172: BAMPTON
Добавлен город 390/1172: BOLTON
Добавлен город 391/1172: ST. HELENS
Добавлен город 392/1172: LETCHWORTH GARDEN CITY
Добавлен город 393/1172: FOLKESTONE
Добавлен город 394/1172: CHESTER
Добавлен город 395/1172: BURRY PORT
Добавлен город 396/1172: MAESTEG
Добавлен город 397/1172: WEDNESBURY
Добавлен город 398/1172: POOLE
Добавлен город 399/1172: TADLEY
Добавлен город 400/1172: HEYWOOD
Добавлен город 401/1172: CRICKHOWELL
Добавлен город 402/1172: BRAINTREE
Добавлен город 403/1172: RIPON
Добавлен город 404/1172: EDGWARE
Добавлен город 405/1172: MOUNTAIN ASH
Добавлен город 406/1172: BOURNE
Добавлен город 407/1172: CLEETHORPES
Добавлен город 408/1172: GOSPORT
Добавлен город 409/1172: LONGFIELD
Добавлен город 410/1172: RUSHDEN
Добавлен город 411/1172: DAVENTRY
Добавлен город 412/1172: RIPLEY
Добавлен город 413/1172: ROSS-ON-WYE
Добавлен город 414/1172: WADEBRIDGE
Добавлен город 415/1172: BICESTER
Добавлен город 416/1172: MELTON CONSTABLE
Добавлен город 417/1172: WITHAM
Добавлен город 418/1172: SANDBACH
Добавлен город 419/1172: NEWENT
Добавлен город 420/1172: BILLERICAY
Добавлен город 421/1172: WORKSOP
Добавлен город 422/1172: OSSETT
Добавлен город 423/1172: TUNBRIDGE WELLS
Добавлен город 424/1172: WHITLEY BAY
Добавлен город 425/1172: YATELEY
Добавлен город 426/1172: ARUNDEL
Добавлен город 427/1172: HENFIELD
Добавлен город 428/1172: OLDBURY
Добавлен город 429/1172: RHYL
Добавлен город 430/1172: TROWBRIDGE
Добавлен город 431/1172: BARROW-IN-FURNESS
Добавлен город 432/1172: INGATESTONE
Добавлен город 433/1172: BORDON
Добавлен город 434/1172: ABINGDON
Добавлен город 435/1172: SCUNTHORPE
Добавлен город 436/1172: HEANOR
Добавлен город 437/1172: LYTHAM ST. ANNES
Добавлен город 438/1172: WOOLACOMBE
Добавлен город 439/1172: CLACTON-ON-SEA
Добавлен город 440/1172: BARNSLEY
Добавлен город 441/1172: ABERAERON
Добавлен город 442/1172: BLAENAU FFESTINIOG
Добавлен город 443/1172: APPLEBY-IN-WESTMORLAND
Добавлен город 444/1172: WEST BROMWICH
Добавлен город 445/1172: RUGBY
Добавлен город 446/1172: THETFORD
Добавлен город 447/1172: LEOMINSTER
Добавлен город 448/1172: HAYWARDS HEATH
Добавлен город 449/1172: LANCING
Добавлен город 450/1172: PWLLHELI
Добавлен город 451/1172: PENRITH
Добавлен город 452/1172: BURY ST. EDMUNDS
Добавлен город 453/1172: TORPOINT
Добавлен город 454/1172: HEXHAM
Добавлен город 455/1172: CULLOMPTON
Добавлен город 456/1172: ELLESMERE
Добавлен город 457/1172: ALFRETON
Добавлен город 458/1172: LUTTERWORTH
Добавлен город 459/1172: CROYDON
Добавлен город 460/1172: CRADLEY HEATH
Добавлен город 461/1172: CHATTERIS
Добавлен город 462/1172: DROITWICH
Добавлен город 463/1172: HITCHIN
Добавлен город 464/1172: WATERLOOVILLE
Добавлен город 465/1172: KNEBWORTH
Добавлен город 466/1172: CAERPHILLY
Добавлен город 467/1172: WIGSTON
Добавлен город 468/1172: NEW MILTON
Добавлен город 469/1172: ORPINGTON
Добавлен город 470/1172: COWES
Добавлен город 471/1172: ALTRINCHAM
Добавлен город 472/1172: SUNBURY-ON-THAMES
Добавлен город 473/1172: BOURNE END
Добавлен город 474/1172: KIDLINGTON
Добавлен город 475/1172: SHEFFORD
Добавлен город 476/1172: ENFIELD
Добавлен город 477/1172: ST. NEOTS
Добавлен город 478/1172: SHIFNAL
Добавлен город 479/1172: BURNHAM-ON-SEA
Добавлен город 480/1172: MINEHEAD
Добавлен город 481/1172: WALTON-ON-THAMES
Добавлен город 482/1172: LEIGHTON BUZZARD
Добавлен город 483/1172: DUDLEY
Добавлен город 484/1172: HYTHE
Добавлен город 485/1172: SURBITON
Добавлен город 486/1172: BEXLEYHEATH
Добавлен город 487/1172: HAILSHAM
Добавлен город 488/1172: ILKESTON
Добавлен город 489/1172: PRUDHOE
Добавлен город 490/1172: SALTBURN-BY-THE-SEA
Добавлен город 491/1172: THATCHAM
Добавлен город 492/1172: ROMNEY MARSH
Добавлен город 493/1172: BERKHAMSTED
Добавлен город 494/1172: CHEADLE
Добавлен город 495/1172: WANTAGE
Добавлен город 496/1172: AMERSHAM
Добавлен город 497/1172: PETERLEE
Добавлен город 498/1172: GLOSSOP
Добавлен город 499/1172: WIMBORNE
Добавлен город 500/1172: CHESSINGTON
Добавлен город 501/1172: GRAVESEND
Добавлен город 502/1172: BENFLEET
Добавлен город 503/1172: ACCRINGTON
Добавлен город 504/1172: NEW MALDEN
Добавлен город 505/1172: RICKMANSWORTH
Добавлен город 506/1172: HORNCASTLE
Добавлен город 507/1172: ELLESMERE PORT
Добавлен город 508/1172: ROMFORD
Добавлен город 509/1172: COLNE
Добавлен город 510/1172: SOUTHALL
Добавлен город 511/1172: HAYES
Добавлен город 512/1172: WORCESTER PARK
Добавлен город 513/1172: MARKET DRAYTON
Добавлен город 514/1172: RAMSGATE
Добавлен город 515/1172: SHOREHAM-BY-SEA
Добавлен город 516/1172: PERSHORE
Добавлен город 517/1172: SKIPTON
Добавлен город 518/1172: TONYPANDY
Добавлен город 519/1172: WALLINGFORD
Добавлен город 520/1172: SITTINGBOURNE
Добавлен город 521/1172: PRESCOT
Добавлен город 522/1172: SOUTHPORT
Добавлен город 523/1172: MITCHAM
Добавлен город 524/1172: BRIGG
Добавлен город 525/1172: SIDCUP
Добавлен город 526/1172: HASSOCKS
Добавлен город 527/1172: STEYNING
Добавлен город 528/1172: WARE
Добавлен город 529/1172: WOKING
Добавлен город 530/1172: LLANDEILO
Добавлен город 531/1172: LLANDUDNO
Добавлен город 532/1172: WALLSEND
Добавлен город 533/1172: HINCKLEY
Добавлен город 534/1172: TRIMDON STATION
Добавлен город 535/1172: IVYBRIDGE
Добавлен город 536/1172: FROME
Добавлен город 537/1172: BROADSTAIRS
Добавлен город 538/1172: ROMSEY
Добавлен город 539/1172: NEWPORT PAGNELL
Добавлен город 540/1172: WELLINGBOROUGH
Добавлен город 541/1172: WELLING
Добавлен город 542/1172: DRIFFIELD
Добавлен город 543/1172: SEAFORD
Добавлен город 544/1172: HIGH WYCOMBE
Добавлен город 545/1172: PEWSEY
Добавлен город 546/1172: AYLESFORD
Добавлен город 547/1172: COULSDON
Добавлен город 548/1172: ALCESTER
Добавлен город 549/1172: SAFFRON WALDEN
Добавлен город 550/1172: STANFORD-LE-HOPE
Добавлен город 551/1172: EXMOUTH
Добавлен город 552/1172: WELWYN GARDEN CITY
Добавлен город 553/1172: WINCHESTER
Добавлен город 554/1172: LICHFIELD
Добавлен город 555/1172: FARNHAM
Добавлен город 556/1172: SHIPLEY
Добавлен город 557/1172: SANDHURST
Добавлен город 558/1172: HENLEY-IN-ARDEN
Добавлен город 559/1172: FAVERSHAM
Добавлен город 560/1172: SHEPPERTON
Добавлен город 561/1172: FALMOUTH
Добавлен город 562/1172: GUNNISLAKE
Добавлен город 563/1172: NESTON
Добавлен город 564/1172: GLASTONBURY
Добавлен город 565/1172: WYMONDHAM
Добавлен город 566/1172: PORTLAND
Добавлен город 567/1172: TIPTON
Добавлен город 568/1172: BARNOLDSWICK
Добавлен город 569/1172: KINGSWINFORD
Добавлен город 570/1172: LANCASTER
Добавлен город 571/1172: LEYLAND
Добавлен город 572/1172: TOWCESTER
Добавлен город 573/1172: NANTWICH

In [23]:
# Распаковываем city_coords в колонки
df['city_lat'] = df['town_city'].map(lambda c: city_coords[c][0])
df['city_lon'] = df['town_city'].map(lambda c: city_coords[c][1])

In [26]:
# Считаем расстояние
df['dist_km'] = haversine(
    df['city_lat'], df['city_lon'],
    df['latitude'], df['longitude']
)

df[['town_city','latitude','longitude','city_lat','city_lon','dist_km']].head()

            town_city   latitude  longitude   city_lat  city_lon   dist_km
0  BISHOP'S STORTFORD  51.895390   0.156180  51.867628  0.163196  3.124343
1           LIVERPOOL  53.432800  -2.909600  53.407199 -2.991680  6.139023
2              SLOUGH  51.502114  -0.551257  51.503427 -0.574872  1.641050
3            BEDWORTH  52.478075  -1.447600  52.479283 -1.466320  1.274898
4            OSWESTRY  52.832861  -2.965928  52.860310 -3.054820  6.704670

In [ ]:
cols = ["town_city", "city_lat", "city_lon", ]
df.to_csv("output_with_coords.csv", columns=cols, index=False)