In [1]:
import pandas as pd

In [2]:
postcode_df = pd.read_csv('./data/postcode_lat_long.csv')
postcode_df

          postcode   latitude  longitude
0         CM23 4PA  51.895390   0.156180
1          L12 0AY  53.432800  -2.909600
2          SL3 8XX  51.502114  -0.551257
3         CV12 8TF  52.478075  -1.447600
4         SY11 1HP  52.832861  -2.965928
...            ...        ...        ...
30074949   NG2 3LH  52.929150  -1.114850
30074950  LE12 6NX  52.781911  -1.184511
30074951  NG17 7JW  53.128367  -1.267683
30074952  NG18 2RN  53.133300  -1.200000
30074953  DN22 0LS  53.315094  -0.907808

[30074954 rows x 3 columns]

In [3]:
postcode_df = postcode_df.drop_duplicates(subset='postcode')
postcode_df

          postcode   latitude  longitude
0         CM23 4PA  51.895390   0.156180
1          L12 0AY  53.432800  -2.909600
2          SL3 8XX  51.502114  -0.551257
3         CV12 8TF  52.478075  -1.447600
4         SY11 1HP  52.832861  -2.965928
...            ...        ...        ...
30068694  PE19 0AR  52.232006  -0.240967
30069973   PO9 3FL  50.850500  -0.990900
30071433   RG7 2NR  51.400358  -1.068564
30071858   CA7 9RY  54.803578  -3.161617
30073036   WV4 4QY  52.561700  -2.160733

[1321470 rows x 3 columns]

In [4]:
postcode_df.to_csv('./data/postcode_lat_long.csv', index=False)

In [5]:
city_df = pd.read_csv('./data/city_lat_long.csv')
city_df

                   town_city   city_lat  city_lon
0         BISHOP'S STORTFORD  51.867628  0.163196
1                  LIVERPOOL  53.407199 -2.991680
2                     SLOUGH  51.503427 -0.574872
3                   BEDWORTH  52.479283 -1.466320
4                   OSWESTRY  52.860310 -3.054820
...                      ...        ...       ...
30124348          NOTTINGHAM  52.953419 -1.149646
30124349        LOUGHBOROUGH  52.772386 -1.207798
30124350          NOTTINGHAM  52.953419 -1.149646
30124351           MANSFIELD  53.144379 -1.196416
30124352             RETFORD  53.323132 -0.942488

[30124353 rows x 3 columns]

In [6]:
city_df = city_df.drop_duplicates(subset='town_city')
city_df

                   town_city   city_lat  city_lon
0         BISHOP'S STORTFORD  51.867628  0.163196
1                  LIVERPOOL  53.407199 -2.991680
2                     SLOUGH  51.503427 -0.574872
3                   BEDWORTH  52.479283 -1.466320
4                   OSWESTRY  52.860310 -3.054820
...                      ...        ...       ...
4247942                KELSO  55.598379 -2.433837
13225148           THORNHILL  55.240658 -3.764921
16815277        BILLINGHURST  51.121594 -0.543263
19350297             GATWICK  51.197090 -0.694312
22989060              BIGGAR  55.624492 -3.521580

[1172 rows x 3 columns]

In [7]:
city_df.to_csv('./data/city_lat_long.csv', index=False)